services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seo-analyzer-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./seo_analyzer.db
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://localhost:5173
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seo-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
